var MENU = {
  cafe: [
    {
      id: "Prensa-Francesa",
      img: "./img/cardapio/cafe/Prensa-Francesa.png",
      name: "Prensa Francesa",
      dsc: "(180ml)  Em uma cafeteira manual é preparado um delicioso café por infusão, mantendo os grãos do café moídos na hora em contato com a água quente traz o resultado mais encorpado, aromático e um sabor mais acentuado",
      price: 13.0,
    },
    {
      id: "coado",
      img: "./img/cardapio/cafe/coado.png",
      name: "Coado",
      dsc: "(180ml) O café coado é uma bebida sem açúcar, suave e equilibrada que envolve a filtragem de água (mineral) quente através dos grãos de café moídos na hora. É servido em uma xícara de porcelana arredondada, acompanhada de um suporte em alumínio e um coador de tecido permitindo você apreciar o aroma e a cor marrom do nosso café.",
      price: 8.0,
    },
    {
      id: "Expresso",
      img: "./img/cardapio/cafe/expresso.png",
      name: "Expresso",
      dsc: "(50ml) Café encorpado com uma crema dourada e de sabor intenso, perfeito para os amantes de um bom expresso.",
      price: 9.0,
    },
  ],
  cappuccinos: [
    {
      id: "Capuccino-Be-Coffee",
      img: "./img/cardapio/cappuccinos/Capuccino-Be-Coffee.png",
      name: "Cappuccino Bê Coffee",
      dsc: "(220ml) Cappucino tradicional com adicional de Nutella e marshmallow tostado deixando-o ainda mais saboroso",
      price: 22.0,
    },
    {
      id: "Capuccino-doce-de-leite",
      img: "./img/cardapio/cappuccinos/Capuccino-doce-de leite.png",
      name: "Cappuccino doce de leite",
      dsc: "(220ml) Cappucino tradicional com adicional de Doce de leite cremoso da casa, deixando-o ainda mais saboroso",
      price: 18.0,
    },
    {
      id: "Capuccino-tradicional",
      img: "./img/cardapio/cappuccinos/Capuccino-tradicional.png",
      name: "Cappuccino tradicional",
      dsc: "(220ml) Bebida deliciosa adoçada a base de café, leite em pó, cacau 50% que traz uma nota sutil de chocolate, a canela deixando um toque de especiarias. Adicionado ao leite vaporizado deixa seu sabor, textura aveludada e com muita cremosidade.",
      price: 13.0,
    },
    {
      id: "Capuccino-italiano",
      img: "./img/cardapio/cappuccinos/cappuccino-italiano.png",
      name: "Cappuccino italiano",
      dsc: "(220ml) Uma combinação equilibrada de café expresso com o leite vaporizado obtemos uma textura suave e cremosa que traz uma sensação aveludada à bebida. Finalizado com cacau e canela. ",
      price: 12.0,
    },
    {
      id: "Capuccino-nutella",
      img: "./img/cardapio/cappuccinos/cappuccino-nutella.png",
      name: "Cappuccino nutella",
      dsc: "(220ml) Cappucino tradicional com adicional de Nutella, deixando o ainda mais saboroso",
      price: 18.0,
    },
  ],
  "chocolate quente": [
    {
      id: "Chocolate-Quente",
      img: "./img/cardapio/chocolate quente/Chocolate-Quente.png",
      name: "Chocolate Quente Cremoso",
      dsc: "(200ml) Você está prestes a se render a uma experiência irresistível e reconfortante, o delicioso Chocolate Quente Cremoso feito com leite integral, creme de leite, açúcar e cacau 50%. Coberto de um creme de chantilly da casa. Perfeito para dias frios e para os momentos de relaxamento.",
      price: 18.0,
    },
    {
      id: "chocolate-becoffe",
      img: "./img/cardapio/chocolate quente/chocolatebecoffee.png",
      name: "Chocolate Bê coffee Cremoso",
      dsc: "(200ml) Chocolate quente cremoso, com Nutella e marshmallow tostado",
      price: 22.0,
    },
  ],
  "bebidas geladas": [
    {
      id: "Cappuccino-Gelado",
      img: "./img/cardapio/bebidas geladas/Cappuccino-Gelado.png",
      name: "Cappuccino Gelado",
      dsc: "(200ml) Uma bebida deliciosa adoçada a base de café, leite em pó, cacau 50% que traz uma nota sutil de chocolate, a canela deixando um toque de especiarias, envolvido ao leite integral e um delicioso sorvete de creme deixando seu sabor, textura aveludada e com muita cremosidade. Coberto por uma leve e doce cobertura do creme do chantilly da casa.",
      price: 18.0,
    },
    {
      id: "Frapê",
      img: "./img/cardapio/bebidas geladas/Frapê.png",
      name: "Frapê",
      dsc: "(250ml) Criado com uma mistura única de ingredientes de alta qualidade, frutas in natura (morango, amora e frutas vermelhas), leite integral, leite condensado e sorvete trazendo uma textura cremosa e sabor irresistível. Uma taça decorada com calda e com cobertura do creme de chantilly da casa. Uma explosão de frescor, doçura e sabor que encanta",
      price: 25.0,
    },
    {
      id: "Soda-italiana",
      img: "./img/cardapio/bebidas geladas/Soda-italiana.png",
      name: "Soda italiana",
      dsc: "(350ml) A soda italiana é uma bebida refrescante, visualmente atraente levemente doce e aromática, que combina água gaseificada com xarope e gelo. Sabores, morango, frutas vermelhas, tangerina, limão siciliano e maça verde.",
      price: 17.0,
    },
  ],
  toasts: [
    {
      id: "toasts-chapa",
      img: "./img/cardapio/toasts/toast-chapa.png ",
      name: "Pão na chapa",
      dsc: "Aquela manteiga que derrete e deixa um sabor todo especial, combinando com o pão de casca rústica, fatias mais grossas e incrivelmente macio",
      price: 7.0,
    },
    {
      id: "toasts-queijo",
      img: "./img/cardapio/toasts/queijo.png",
      name: "Pão na chapa com queijo especial",
      dsc: "Aquela manteiga que derrete e deixa um sabor todo especial, combinando com o pão de casca rústica, fatias mais grossas e incrivelmente macio com adicional de queijo minas derretido proporcionando mais sabor ao pão",
      price: 11.0,
    },
    {
      id: "toasts-ovo",
      img: "./img/cardapio/toasts/toastsovos.png",
      name: "Pão na chapa com ovos mexidos e bacon",
      dsc: "Aquela manteiga que derrete e deixa um sabor todo especial, combinando com o pão de casca rústica, fatias mais grossas e incrivelmente macio com adicional de ovo e cubinhos de bacon frito  proporcionando mais sabor ao pão",
      price: 14.0,
    },
    {
      id: "paodequeijo",
      img: "/img/cardapio/salgados/paodequeijo.png",
      name: "Pão de queijo",
      dsc: "(5 unidades) Crocante por fora e macio por dentro, o pão de queijo é uma explosão de sabor e textura, com aquele gostinho caseiro de queijo minas ",
      price: 9.0,
    },
  ],
  salgados: [
    {
      id: "Camarao-Caravelas",
      img: "./img/cardapio/salgados/camaraocaravelas2.png",
      name: "Camarão Caravelas",
      dsc: "(5 unidades) Camarões envolvidos em uma massa feita com um delicioso caldo de camarão e especiarias como cebola, alho e coentro. Acompanha geleia de pimenta, azeite e ou pimenta.",
      price: 17.0,
    },
    {
      id: "Coxinha",
      img: "./img/cardapio/salgados/coxinhas.png",
      name: "Coxinhas na cama de requeijão",
      dsc: "(6 unidades) Massa crocante por fora, um recheio suculento de frango desfiado sobre uma generosa camada de requeijão",
      price: 11.50,
    },
    {
      id: "Cuzcuz-de-milho",
      img: "./img/cardapio/salgados/Cuzcuz-de-milho.png",
      name: "Cuzcuz de milho",
      dsc: "É um prato saudável, preparado com farinha flocada previamente hidratada com água e cozida sobre calor e pode ser harmonizado com os nossos recheios como um suculento frango desfiado, saborosa carne seca dessalgada e desfiadíssima, bacon cortadinho e frito, banana da terra docinha, saborosa manteiga, delicioso requeijão cremoso, queijo minas derretido e até ovo frito",
      price: 14.0,
    },
    {
      id: "Empadao-de-Frango",
      img: "./img/cardapio/salgados/Empadao-de-Frango.png",
      name: "Empadão de Frango",
      dsc: "(Fatia) O clássico empadão é feito com uma massa leve que derrete na boca e um delicioso recheio de frango com especiarias como alho, cebola e açafrão coberto de uma generosa camada de requeijão cremoso",
      price: 16.0,
    },
    {
      id: "Bolinhos-de-bacalhau",
      img: "./img/cardapio/salgados/bolinho.png",
      name: "Bolinhos de bacalhau",
      dsc: "(3 unidades) Bacalhau desfiado com um toque leve de purê de batatas com o coentro e tem como acompanhamento azeite, pimenta e geleia de pimenta.",
      price: 21.0,
    },
    {
      id: "Porção-de-canudinho",
      img: "./img/cardapio/salgados/Porção-de-canudinho.png",
      name: "Canudinho artesanal",
      dsc: "(6 unidades) Nossos canudinhos, preparados com uma massa leve e bem sequinhos, são perfeitos para os acompanhamentos como patê de frango, doce de leite e Nutella.",
      price: 12.0,
    },
    {
      id: "Quibe-artesanal",
      img: "./img/cardapio/salgados/Quibe-artesanal.png",
      name: "Quibe artesanal",
      dsc: "O preparo do quibe, consiste na mistura do triguilho com a carne moída, regado com especiarias aromáticas, o alho, cebola e muita hortelã. Assado no azeite e servido com o delicioso molho cítrico a base de iogurte natural, azeite extravirgem e hortelã.",
      price: 15.0,
    },
  ],
  tapiocas: [
    {
      id: "Tapioca",
      img: "./img/cardapio/tapiocas/Tapioca.png",
      name: "Tapioca 1 ingrediente",
      dsc: "A tapioca é um prato em que a goma é aquecida na frigideira e que servimos com diversos recheios, como um suculento frango desfiado, saborosa carne seca dessalgada e desfiadíssima, bacon cortadinho e frito, creme de aipim pastoso, banana da terra docinha, delicioso requeijão cremoso e queijo minas derretido. Para pedidos com mais de 4 ingredientes, será acrescentado um valor de 2 reais ",
      price: 15.0,
    },
    {
      id: "Tapioca-2",
      img: "./img/cardapio/tapiocas/Tapioca.png",
      name: "Tapioca 2 ingredientes",
      dsc: "A tapioca é um prato em que a goma é aquecida na frigideira e que servimos com diversos recheios, como um suculento frango desfiado, saborosa carne seca dessalgada e desfiadíssima, bacon cortadinho e frito, creme de aipim pastoso, banana da terra docinha, delicioso requeijão cremoso e queijo minas derretido. Para pedidos com mais de 4 ingredientes, será acrescentado um valor de 2 reais ",
      price: 18.0,
    },
    {
      id: "Tapioca-3",
      img: "./img/cardapio/tapiocas/Tapioca.png",
      name: "Tapioca 3 ingredientes",
      dsc: "A tapioca é um prato em que a goma é aquecida na frigideira e que servimos com diversos recheios, como um suculento frango desfiado, saborosa carne seca dessalgada e desfiadíssima, bacon cortadinho e frito, creme de aipim pastoso, banana da terra docinha, delicioso requeijão cremoso e queijo minas derretido. Para pedidos com mais de 4 ingredientes, será acrescentado um valor de 2 reais ",
      price: 21.0,
    },
    {
      id: "Crepioca",
      img: "./img/cardapio/tapiocas/crepioca.jpg",
      name: "Crepioca 1 ingrediente",
      dsc: "A crepioca é uma excelente alternativa leve para quem busca um café da tarde. Mistura homogênea da goma de tapioca, ovo e uma pitada de sal em uma frigideira com azeite extravirgem e recheada com os nossos recheios, como suculento frango desfiado, saborosa carne seca dessalgada e desfiadíssima, bacon cortadinho e frito, creme de aipim pastoso, banana da terra docinha, delicioso requeijão cremoso e queijo minas derretido. Para pedidos com mais de 4 ingredientes, será acrescentado um valor de 2 reais ",
      price: 16.0,
    },
    {
      id: "Crepioca-2",
      img: "./img/cardapio/tapiocas/crepioca.jpg",
      name: "Crepioca 2 ingredientes",
      dsc: "A crepioca é uma excelente alternativa leve para quem busca um café da tarde. Mistura homogênea da goma de tapioca, ovo e uma pitada de sal em uma frigideira com azeite extravirgem e recheada com os nossos recheios, como suculento frango desfiado, saborosa carne seca dessalgada e desfiadíssima, bacon cortadinho e frito, creme de aipim pastoso, banana da terra docinha, delicioso requeijão cremoso e queijo minas derretido. Para pedidos com mais de 4 ingredientes, será acrescentado um valor de 2 reais ",
      price: 19.0,
    },
    {
      id: "Crepioca-3",
      img: "./img/cardapio/tapiocas/crepioca.jpg",
      name: "Crepioca 3 ingredientes",
      dsc: "A crepioca é uma excelente alternativa leve para quem busca um café da tarde. Mistura homogênea da goma de tapioca, ovo e uma pitada de sal em uma frigideira com azeite extravirgem e recheada com os nossos recheios, como suculento frango desfiado, saborosa carne seca dessalgada e desfiadíssima, bacon cortadinho e frito, creme de aipim pastoso, banana da terra docinha, delicioso requeijão cremoso e queijo minas derretido. Para pedidos com mais de 4 ingredientes, será acrescentado um valor de 2 reais ",
      price: 22.0,
    },
  ],
  tortas: [
    {
      id: "Banoffee",
      img: "./img/cardapio/tortas/Banoffee.png",
      name: "Banoffee",
      dsc: "(Fatia) A torta é feita com uma deliciosa massa crocante de biscoito, camada generosa de doce de leite cremoso da casa e bananas in natura cobertos com um levíssimo à base de creme e leite condensado, e finalizado com um delicado toque aveludado de canela.",
      price: 21.0,
    },
    {
      id: "Torta-de-limao",
      img: "./img/cardapio/tortas/Torta-de-limao.png",
      name: "Torta de limão",
      dsc: "(Fatia)Deliciosa massa crocante de biscoito com um mousse de limão que derrete na boca com um gostinho cítrico e coberto por uma generosa camada de creme, leite condensado e leite em pó. Essa torta de leveza e frescor é uma explosão de sabor combinado com uma delicada decoração de raspas de limão.",
      price: 21.0,
    },
    {
      id: "Torta-holandesa",
      img: "./img/cardapio/tortas/tortaholandesa.png",
      name: "Torta holandesa",
      dsc: "(Fatia) Essa torta une a crocância da massa de biscoito à suavidade do creme espesso à base de creme e leite condensado, finalizada com uma deliciosa cobertura de ganache e biscoitos com chocolate.",
      price: 22.0,
    },
    {
      id: "Tortamaracuja",
      img: "./img/cardapio/tortas/tortamaracuja.png",
      name: "Torta de maracujá",
      dsc: "(Fatia) Uma crocante massa de biscoitos com um delicioso creme de maracujá coberto por uma generosa camada de creme, leite condensado e leite em pó. E uma camada refrescante e tropical de geleia de maracujá in natura.",
      price: 22.0,
    },
  ],
  bolos: [
    {
      id: "Chocolatudo",
      img: "./img/cardapio/bolos/Chocolatudo.png",
      name: "Chocolatudo",
      dsc: "(Fatia) Um bolo leve e úmido preparado com cacau 50% e recheio generoso de brigadeiro e uma ganache de creme e chocolate, finalizado com uma deliciosa ganache de chocolate.",
      price: 23.0,
    },
    {
      id: "Ninho-com-morango",
      img: "./img/cardapio/bolos/bolo-de-ninho.jpg",
      name: "Ninho com morango",
      dsc: "(Fatia) Uma combinação deliciosa, este bolo é feito com uma massa macia e fofinha, recheado com um saboroso creme de ninho e um cremoso couli de morangos. É coberto por uma deliciosa camada quatro leites.",
      price: 23.0,
    },
    {
      id: "Red-Velvet",
      img: "./img/cardapio/bolos/Red-Velvet.png",
      name: "Red Velvet",
      dsc: "(Fatia) Um bolo americano famoso por sua cor vermelha vibrante e textura macia. É recheado com uma generosa camada de cream cheese, que equilibra perfeitamente com a cobertura cremosa de quatro leites acompanhada de uma deliciosa geleia de frutas vermelhas.",
      price: 25.0,
    },
  ],
  Doces: [
    {
      id: "Brownie-com-sorvete",
      img: "./img/cardapio/Doces/Brownie-com-sorvete.png",
      name: "Brownie com sorvete",
      dsc: "O nosso brownie é uma massa cremosa, densa e rica em chocolate. É aquecido e servido quente com uma ganache de chocolate artesanal e uma deliciosa bola de sorvete.",
      price: 23.0,
    },
    {
      id: "Porção-mini-churros",
      img: "./img/cardapio/Doces/Porção-mini-churros.png",
      name: "Porção mini churros",
      dsc: "(15 unidades) Nosso delicioso mini churro de massa artesanal bem sequinho coberto de açúcar e canela acompanhado do Doce de leite da casa e Nutella.",
      price: 22.0,
    },
    {
      id: "banana-real",
      img: "./img/cardapio/Doces/banana-real2.png",
      name: "Banana real",
      dsc: "A deliciosa banana real é um pastel frito e recheado com uma caramelada banana-da-terra, salpicado com açúcar e canela, que é uma sobremesa clássica da culinária baiana",
      price: 9.0,
    },
    {
      id: "palha-italiana",
      img: "./img/cardapio/Doces/palha-italiana2.png",
      name: "Palha Italiana",
      dsc: "A palha italiana idealizada para os apaixonados por chocolate que buscam uma experiência gustativa. É um doce moldado à mão, feito com o nosso delicioso brigadeiro e pedaços de biscoitos.",
      price: 9.5,
    },
    {
      id: "docinho",
      img: "./img/cardapio/Doces/docinho2.png",
      name: "Brigadeiro",
      dsc: "(36g) É um brigadeiro diferenciado, feito com leite condensado, creme de leite e cacau 50%. Um doce macio, redondo coberto por uma camada de um saboroso granulado ao leite.",
      price: 4.5,
    },
  ],

  bebidas: [
    {
      id: "Agua-com-gas",
      img: "./img/cardapio/bebidas/Agua-com-gas.png",
      name: "Água com gás",
      dsc: "(500ml) A água com gás engarrafada, geladinha, melhora o paladar deixando as papilas gustativas mais sensíveis ao sabor dos alimentos.(Acréscimo de limão e gelo 0,50 centavos)",
      price: 5.0,
    },
    {
      id: "Agua",
      img: "./img/cardapio/bebidas/Agua.png",
      name: "Água Mineral",
      dsc: "(500ml) Água engarrafada, geladinha e essencial para acompanhar seu prato.",
      price: 4.0,
    },
    {
      id: "Refrigerante-latas",
      img: "./img/cardapio/bebidas/Refrigerante-latas.png",
      name: "Refrigerante",
      dsc: "(lata) unidade",
      price: 6.5,
    },
    {
      id: "suco",
      img: "./img/cardapio/bebidas/suco.png",
      name: "Sucos",
      dsc: "(300ml)A polpa de fruta natural congelada é batida com água mineral gelada com ou sem açúcar proporcionando um suco extremamente gelado e concentrado. Sabores, acerola, graviola, cajá, cupuaçu, goiaba, mangaba",
      price: 8.0,
    },
  ],
  pratos: [
    {
      id: "camarao-internacional",
      img: "./img/cardapio/caldos/camaraoint.png",
      name: "Camarão internacional",
      dsc: "(500g) Camarões salteados no azeite e manteiga, envolvidos em um cremoso arroz feito no leve molho de requeijão com ervilhas, presunto, queijo e coberto com batata palha e queijo.",
      price: 47.0,
    },
  ],
};
